name: Artifact Release Upload

env:
  APP_NAME: dot-of-doom
  MAIN_LOCATION: bin/dart.dart
on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    env:
      OUTPUT_PATH: ${{ APP_NAME }}-${{ matrix.os }}.zip
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Compile and Zip
        run: |
            dart compile exe ${{ MAIN_LOCATION }} -o $APP_NAME
            zip ${{ OUTPUT_PATH }} config.template.yml
      - uses: softprops/action-gh-release@v1
        with:
          path: ${{ OUTPUT_PATH }}
        env:
          GITHUB_TOKEN: ${{ CI_CD }}
        
