name: Artifact Release Upload

on:
  release:
    types: [created]

env:
  APP_NAME: dot-of-doom
  MAIN_LOCATION: bin/dart.dart

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Compile and Zip
        run: |
            OUTPUT_PATH="${{ env.APP_NAME }}-${{ matrix.os }}.zip"
            dart compile exe ${{ env.MAIN_LOCATION }} -o ${{ env.APP_NAME }}
            zip "$OUTPUT_PATH" "${{ env.APP_NAME }}" config.template.yml README.md run.sh
      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APP_NAME }}-${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}
        
