name: Dart

env:
  APP_NAME: dot-of-doom
  MAIN_LOCATION: bin/dart.dart
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Compile and Zip
        run: |
            dart compile exe $MAIN_LOCATION -o $APP_NAME
            zip dot-of-doom-${{ matrix.os }}.zip $APP_NAME config.template.yml
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dot-of-doom-${{ matrix.os }}.zip
      - name: Analyze project source
        run: dart analyze
        
