name: Auto Release

on:
  push:
    branches:
      - main

env:
  MAJ_VER: 1
  MIN_VER: 2

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $TAG
          name: Release $TAG
        env:
          TAG: v$MAJ_VER.$MIN_VER.${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.CI_CD }}
