name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7' # Or use .ruby-version
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build
        run: |
          ./build.sh
      - name: Set up Git
        run: |
          git fetch --tags
      - name: Get latest tag and compute next version
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          next_patch=$((patch + 1))
          next_tag="v$major.$minor.$next_patch"
          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.next_tag }}
          name: Release ${{ steps.get_tag.outputs.next_tag }}
          files: |
                 build/dot-of-doom.zip
          body: |
            Auto-generated release from ubuntu runner
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}          
