name: Upload Release Artifact

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build
        run: |
          ./build.sh
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: Release ${{ github.event.release.tag_name }}
          files: |
                 build/dot-of-doom-${{ matrix.ruby-version }}.zip
          body: |
            Auto-uploaded artifact for draft release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}          
