name: Ruby

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Or use .ruby-version
      - name: Install dependencies
        run: bundle install
      - name: Build macOS Application (Example with a custom script)
        run: |
          mkdir -p build/DotOfDoom.app/Contents/MacOS
          ls
          cp src/TextSender.rb build/DotOfDoom.app/Contents/MacOS/
          echo '#!/bin/bash' > build/DotOfDoom.app/Contents/MacOS/runner
          echo 'ruby "$0/../src/TextSender.rb"' >> build/DotOfDoom.app/Contents/MacOS/runner
          chmod +x build/DotOfDoom.app/Contents/MacOS/runner
          # Add Info.plist and other necessary files for a proper .app bundle
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.CI_CD }}
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Please work
          draft: true
          prerelease: true
      - name: Upload macOS Application
        uses: actions/upload-artifact@v4
        with:
          name: DotOfDoom-macOS
          path: build/DotOfDoom.app
      - name: upload macOS artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/DotOfDoom.app
          asset_name: DotOfDoom.app
          asset_content_type: application/app
