name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create ZIP of source code
        run: |
          mkdir -p release
          zip -r release/source-code.zip . -x "*.git*" "*.github*"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Or use .ruby-version
      - name: Install dependencies
        run: bundle install
      - name: Build macOS Application (Example with a custom script)
        run: |
          mkdir -p build/DotOfDoom.app/Contents/MacOS
          ls
          cp src/TextSender.rb build/DotOfDoom.app/Contents/MacOS/
          echo '#!/bin/bash' > build/DotOfDoom.app/Contents/MacOS/runner
          echo 'ruby "$0/../src/TextSender.rb"' >> build/DotOfDoom.app/Contents/MacOS/runner
          chmod +x build/DotOfDoom.app/Contents/MacOS/runner
          # Add Info.plist and other necessary files for a proper .app bundle
      - name: Set up Git
        run: |
          git fetch --tags
      - name: Get latest tag and compute next version
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          next_patch=$((patch + 1))
          next_tag="v$major.$minor.$next_patch"
          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT
      - name: Zip macOS app
        run: zip -r DotOfDoom-macOS.zip build/DotOfDoom.app
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.next_tag }}
          name: Release ${{ steps.get_tag.outputs.next_tag }}
          files: |
                 DotOfDoom-macOS.zip
                 release/source-code.zip
          body: |
            Auto-generated release from macOS runner
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}
      - name: Debug upload_url
        run: |
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
          
