name: Tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push tag
        run: |
          version="v1.2.3"
          git tag "$version"
          git push origin "$version"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}
